// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: clawman/v1/clawman.proto

package clawmanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Clawman_RoomChat_FullMethodName = "/clawman.v1.Clawman/RoomChat"
)

// ClawmanClient is the client API for Clawman service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClawmanClient interface {
	RoomChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type clawmanClient struct {
	cc grpc.ClientConnInterface
}

func NewClawmanClient(cc grpc.ClientConnInterface) ClawmanClient {
	return &clawmanClient{cc}
}

func (c *clawmanClient) RoomChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Clawman_ServiceDesc.Streams[0], Clawman_RoomChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Clawman_RoomChatClient = grpc.BidiStreamingClient[Message, Message]

// ClawmanServer is the server API for Clawman service.
// All implementations must embed UnimplementedClawmanServer
// for forward compatibility.
type ClawmanServer interface {
	RoomChat(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedClawmanServer()
}

// UnimplementedClawmanServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClawmanServer struct{}

func (UnimplementedClawmanServer) RoomChat(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Errorf(codes.Unimplemented, "method RoomChat not implemented")
}
func (UnimplementedClawmanServer) mustEmbedUnimplementedClawmanServer() {}
func (UnimplementedClawmanServer) testEmbeddedByValue()                 {}

// UnsafeClawmanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClawmanServer will
// result in compilation errors.
type UnsafeClawmanServer interface {
	mustEmbedUnimplementedClawmanServer()
}

func RegisterClawmanServer(s grpc.ServiceRegistrar, srv ClawmanServer) {
	// If the following call pancis, it indicates UnimplementedClawmanServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Clawman_ServiceDesc, srv)
}

func _Clawman_RoomChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClawmanServer).RoomChat(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Clawman_RoomChatServer = grpc.BidiStreamingServer[Message, Message]

// Clawman_ServiceDesc is the grpc.ServiceDesc for Clawman service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clawman_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawman.v1.Clawman",
	HandlerType: (*ClawmanServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RoomChat",
			Handler:       _Clawman_RoomChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "clawman/v1/clawman.proto",
}
