// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: clawman/v1/clawman.proto

package clawmanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	SandboxId     string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Messages      []*AgentMessage        `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	Output        string                 `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_clawman_v1_clawman_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_clawman_v1_clawman_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_clawman_v1_clawman_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Message) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *Message) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Message) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Message) GetMessages() []*AgentMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Message) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Message) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Msgid         string                 `protobuf:"bytes,2,opt,name=msgid,proto3" json:"msgid,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	FromId        string                 `protobuf:"bytes,4,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName      string                 `protobuf:"bytes,5,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	MsgTime       string                 `protobuf:"bytes,6,opt,name=msg_time,json=msgTime,proto3" json:"msg_time,omitempty"`
	Payload       string                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_clawman_v1_clawman_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_clawman_v1_clawman_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_clawman_v1_clawman_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AgentMessage) GetMsgid() string {
	if x != nil {
		return x.Msgid
	}
	return ""
}

func (x *AgentMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AgentMessage) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *AgentMessage) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *AgentMessage) GetMsgTime() string {
	if x != nil {
		return x.MsgTime
	}
	return ""
}

func (x *AgentMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_clawman_v1_clawman_proto protoreflect.FileDescriptor

const file_clawman_v1_clawman_proto_rawDesc = "" +
	"\n" +
	"\x18clawman/v1/clawman.proto\x12\n" +
	"clawman.v1\"\xd8\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x124\n" +
	"\bmessages\x18\x05 \x03(\v2\x18.clawman.v1.AgentMessageR\bmessages\x12\x16\n" +
	"\x06output\x18\x06 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xba\x01\n" +
	"\fAgentMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x14\n" +
	"\x05msgid\x18\x02 \x01(\tR\x05msgid\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x17\n" +
	"\afrom_id\x18\x04 \x01(\tR\x06fromId\x12\x1b\n" +
	"\tfrom_name\x18\x05 \x01(\tR\bfromName\x12\x19\n" +
	"\bmsg_time\x18\x06 \x01(\tR\amsgTime\x12\x18\n" +
	"\apayload\x18\a \x01(\tR\apayload2C\n" +
	"\aClawman\x128\n" +
	"\bRoomChat\x12\x13.clawman.v1.Message\x1a\x13.clawman.v1.Message(\x010\x01B)Z'tinyclaw/proto/gen/clawman/v1;clawmanv1b\x06proto3"

var (
	file_clawman_v1_clawman_proto_rawDescOnce sync.Once
	file_clawman_v1_clawman_proto_rawDescData []byte
)

func file_clawman_v1_clawman_proto_rawDescGZIP() []byte {
	file_clawman_v1_clawman_proto_rawDescOnce.Do(func() {
		file_clawman_v1_clawman_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clawman_v1_clawman_proto_rawDesc), len(file_clawman_v1_clawman_proto_rawDesc)))
	})
	return file_clawman_v1_clawman_proto_rawDescData
}

var file_clawman_v1_clawman_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clawman_v1_clawman_proto_goTypes = []any{
	(*Message)(nil),      // 0: clawman.v1.Message
	(*AgentMessage)(nil), // 1: clawman.v1.AgentMessage
}
var file_clawman_v1_clawman_proto_depIdxs = []int32{
	1, // 0: clawman.v1.Message.messages:type_name -> clawman.v1.AgentMessage
	0, // 1: clawman.v1.Clawman.RoomChat:input_type -> clawman.v1.Message
	0, // 2: clawman.v1.Clawman.RoomChat:output_type -> clawman.v1.Message
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clawman_v1_clawman_proto_init() }
func file_clawman_v1_clawman_proto_init() {
	if File_clawman_v1_clawman_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clawman_v1_clawman_proto_rawDesc), len(file_clawman_v1_clawman_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clawman_v1_clawman_proto_goTypes,
		DependencyIndexes: file_clawman_v1_clawman_proto_depIdxs,
		MessageInfos:      file_clawman_v1_clawman_proto_msgTypes,
	}.Build()
	File_clawman_v1_clawman_proto = out.File
	file_clawman_v1_clawman_proto_goTypes = nil
	file_clawman_v1_clawman_proto_depIdxs = nil
}
