CREATE TABLE IF NOT EXISTS rooms (
	id BIGSERIAL PRIMARY KEY,
	tenant_id TEXT NOT NULL,
	channel TEXT NOT NULL,
	channel_room_id TEXT NOT NULL,
	channel_room_type TEXT NOT NULL,
	display_name TEXT,
	trigger_policy JSONB,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE (tenant_id, channel, channel_room_id)
);

CREATE TABLE IF NOT EXISTS messages (
	id BIGSERIAL PRIMARY KEY,
	room_id BIGINT NOT NULL REFERENCES rooms(id),
	source_message_id TEXT NOT NULL,
	sender_id TEXT NOT NULL,
	sender_name TEXT,
	payload JSONB NOT NULL,
	message_time TIMESTAMPTZ NOT NULL,
	skipped BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE (room_id, source_message_id)
);

CREATE TABLE IF NOT EXISTS invocations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	room_id BIGINT NOT NULL REFERENCES rooms(id),
	status SMALLINT NOT NULL,
	trigger_message_id BIGINT REFERENCES messages(id),
	start_message_id BIGINT REFERENCES messages(id),
	last_seen_message_id BIGINT REFERENCES messages(id),
	error_detail TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	started_at TIMESTAMPTZ,
	completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS deliveries (
	id BIGSERIAL PRIMARY KEY,
	room_id BIGINT NOT NULL REFERENCES rooms(id),
	invocation_id BIGINT NOT NULL REFERENCES invocations(id),
	payload JSONB NOT NULL,
	status SMALLINT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	acked_at TIMESTAMPTZ
);

ALTER TABLE messages
	ADD COLUMN IF NOT EXISTS skipped BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE messages
	DROP COLUMN IF EXISTS dispatch_state;

ALTER TABLE invocations
	ADD COLUMN IF NOT EXISTS start_message_id BIGINT REFERENCES messages(id),
	ADD COLUMN IF NOT EXISTS last_seen_message_id BIGINT REFERENCES messages(id),
	ADD COLUMN IF NOT EXISTS error_detail TEXT;

ALTER TABLE invocations
	DROP COLUMN IF EXISTS input_snapshot,
	DROP COLUMN IF EXISTS output_snapshot;
